steps:
  # Build user-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/triple-method-453308-v7/user-service', './user-service']
  
  # Build institution-service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/triple-method-453308-v7/notification-service', './notification-service']

  # Push images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/triple-method-453308-v7/user-service']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/triple-method-453308-v7/notification-service']

images:
  - 'gcr.io/triple-method-453308-v7/user-service'
  - 'gcr.io/triple-method-453308-v7/notification-service'
